image: alpine:latest

variables:
  POSTGRES_ENABLED: "false"

  KUBERNETES_VERSION: 1.11.10
  HELM_VERSION: 2.14.0

  DOCKER_DRIVER: overlay2

  ROLLOUT_RESOURCE_TYPE: deployment

stages:
  - build
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

build:
  image: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:build
  script:
    - CARGO_HOME="$(pwd)/cargo_home" cargo build --release
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - cargo_home/
      - target/

bootstrap:
  image: docker:stable
  stage: build
  when: manual
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - ./build_bootstrap.sh

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml