FROM rust:slim-buster

RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get -y install ca-certificates libpq-dev libpq5 && \
cargo install --force diesel_cli --no-default-features --features "postgres"
