-- Your SQL goes here
CREATE TABLE tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGSERIAL NOT NULL,
    token TEXT UNIQUE NOT NULL,
    created_when TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)